spring:
  application:
    name: books-service

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/demodatabase?createDatabaseIfNotExist=true
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8090